# Generated by Django 4.2.3 on 2023-07-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_employee_alter_inventory_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
